The ``7-base_geometry`` module
======================

Using ''BaseGeometry''
-------------------
First import
      >>> BaseGeometry = __import__('7-base_geometry').BaseGeometry

Bg variable:

      >>> bg = BaseGeometry()

Base test:

     >>> bg.integer_validator("my_int", 12)

Test zero number:

     >>> bg.integer_validator("my_int", 0)
     Traceback (most recent call last):
     ...
     ValueError: my_int must be greater than 0

Test negatve number:

     >>> bg.integer_validator("my_int", -1)
     Traceback (most recent call last):
     ...
     ValueError: my_int must be greater than 0

Test float number:

     >>> bg.integer_validator("my_int", 2.5)
     Traceback (most recent call last):
     ...
     TypeError: my_int must be an integer

Test string number:

     >>> bg.integer_validator("my_int", "string")
     Traceback (most recent call last):
     ...
     TypeError: my_int must be an integer

Test boolean number:

     >>> bg.integer_validator("my_int", True)
     Traceback (most recent call last):
     ...
     TypeError: my_int must be an integer

Test infinite number:

     >>> bg.integer_validator("my_int", True)
     Traceback (most recent call last):
     ...
     TypeError: my_int must be an integer

Test not a number:

     >>> bg.integer_validator("my_int", float('nan'))
     Traceback (most recent call last):
     ...
     TypeError: my_int must be an integer

Test type:

     >>> type(bg) == BaseGeometry
     True

Test type method:

     >>> type(BaseGeometry.__dict__['area'])
     <class 'function'>

Area method called via class with no args:

     >>> bg.__class__.area()
     Traceback (most recent call last):
     TypeError: area() missing 1 required positional argument: 'self'

Area method args test (1 arg):

     >> bg.area(10)
     Traceback (most recent call last):
     TypeError: area() takes 1 positional argument but 2 were given

Area method normal test:

     >>> bg.area()
     Traceback (most recent call last):
     Exception: area() is not implemented

integer_validator method called via class with no args:

     >>> bg.__class__.integer_validator()
     Traceback (most recent call last):
     TypeError: integer_validator() missing 3 required positional arguments: 'self', 'name', and 'value'

Area method normal test:

    >>> bg.area()
    Traceback (most recent call last):
    Exception: area() is not implemented


